version: "3.8"

services:
    spa-template:
        container_name: spa-template
        image: spa-template
        restart: always
        build:
            context: .
        volumes:
            - ./src:/app/src
        ports:
            - 80:80
